export const HOME_STACK = 'HOME_STACK'
export const SESSION_STACK = 'Session'
export const CHAT_STACK = 'Chat'
export const VIDEO_STACK = 'Video'
export const AUDIO_STACK = 'Audioroom'
export const VBOOK_STACK = 'Vbook'